version: "2"

services:
  lt:
    build: .
    ports:
      - 5000:5000
    environment:
      - DB_HOST=mysql
  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=lt
    ports:
      - 3306:3306
    volumes:
      - mysql:/var/lib/mysql
volumes:
  mysql:
