"""empty message

Revision ID: 47442e478395
Revises: 71abeff09960
Create Date: 2018-07-06 23:58:56.333281

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47442e478395'
down_revision = '71abeff09960'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lt',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('talk',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('lt_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('presentation_time', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('talk')
    op.drop_table('lt')
    # ### end Alembic commands ###
